server:
  port: 8081

spring:
  profiles:
    default: local
  application:
    name: board-admin-server

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace

jwt:
  secret: ${JWT_SECRET}
