spring:
  profiles:
    default: local
  application:
    name: multi-board

  data:
    web:
      pageable:
        default-page-size: 3
        max-page-size: 1000
    redis:
      host: localhost
      port: 6379
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 30MB

  mail:
    host: localhost
    port: 25         # FakeSMTP 실행 포트
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace

jwt:
  secret: ${JWT_SECRET}

app:
  frontend:
    base-url: "http://localhost:5173"
  password-reset:
    redis-prefix: "pwd-reset:"
    expiry-time: 30m
    reset-url: "${app.frontend.base-url}/password-reset/confirm/"
  file:
    dir: "${user.dir}/uploads/files"
  internal:
    auth:
      secret: "${INTERNAL_SECRET}"

