server:
  port: 8082

spring:
  profiles:
    default: local
  application:
    name: board-batch-server

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
